name: mattdom
favicon: null
layout_spectrum: 0.990953
typography_spectrum: 0.7435746817405372
title: Matt D.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.030230849828503548
  lightness: 0.5368372187734621
  saturation: 0.7138348603848585
  rhythmicContrast: 0.8282671724594095
purpose:
  - name: null
    item: null
    url: null
